### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by CreativExit** [v-checha/node-typescript-mongodb#18]
Hi, 

I try to deploy this project in Heroku and have this error:

internal/modules/cjs/loader.js:1021
2020-01-15T19:53:55.814455+00:00 app[web.1]:   return process.dlopen(module, path.toNamespacedPath(filename));
2020-01-15T19:53:55.814460+00:00 app[web.1]:                  ^
2020-01-15T19:53:55.814463+00:00 app[web.1]: 
2020-01-15T19:53:55.814465+00:00 app[web.1]: Error: /app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
2020-01-15T19:53:55.814468+00:00 app[web.1]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
2020-01-15T19:53:55.814470+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:811:32)
2020-01-15T19:53:55.814472+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
2020-01-15T19:53:55.814474+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:848:19)
2020-01-15T19:53:55.814476+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-01-15T19:53:55.814478+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/bcrypt/bcrypt.js:6:16)
2020-01-15T19:53:55.814480+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
2020-01-15T19:53:55.814483+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
2020-01-15T19:53:55.814485+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:811:32)
2020-01-15T19:53:55.814487+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
2020-01-15T19:53:55.814489+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:848:19)
2020-01-15T19:53:55.814491+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-01-15T19:53:55.814493+00:00 app[web.1]:     at Object.<anonymous> (/app/build/components/User/model.js:11:16)
2020-01-15T19:53:55.814495+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
2020-01-15T19:53:55.814497+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
2020-01-15T19:53:55.814499+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:811:32)

Thanks

**Comment by v-checha** [comment]
@CreativExit Hey, sorry, but I did not see an error in our template application in your stack trace. Did you resolve your issue?
